"""Tests for FileGenerator."""
import pytest
from pathlib import Path
from agents.scaffolder.file_generator import FileGenerator, ScaffoldError
from agents.scaffolder.structure_generator import RenderedFile


def test_writes_file_to_disk(tmp_path):
    gen = FileGenerator()
    files = [RenderedFile(relative_path="src/main.py", content="print('hello')\n", header=True)]
    written = gen.write(files, tmp_path, spec_id="spec_001")
    assert len(written) == 1
    assert (tmp_path / "src" / "main.py").exists()


def test_header_prepended_for_py(tmp_path):
    gen = FileGenerator()
    files = [RenderedFile(relative_path="main.py", content="pass\n", header=True)]
    gen.write(files, tmp_path, spec_id="spec_001")
    first_line = (tmp_path / "main.py").read_text().splitlines()[0]
    assert first_line == "# Generated by Scaffolder Agent from spec spec_001"


def test_header_prepended_for_ts(tmp_path):
    gen = FileGenerator()
    files = [RenderedFile(relative_path="index.ts", content="export {}\n", header=True)]
    gen.write(files, tmp_path, spec_id="spec_001")
    first_line = (tmp_path / "index.ts").read_text().splitlines()[0]
    assert first_line == "// Generated by Scaffolder Agent from spec spec_001"


def test_no_header_when_header_false(tmp_path):
    gen = FileGenerator()
    files = [RenderedFile(relative_path="pyproject.toml", content="[project]\n", header=False)]
    gen.write(files, tmp_path, spec_id="spec_001")
    content = (tmp_path / "pyproject.toml").read_text()
    assert content.startswith("[project]")


def test_no_header_for_unsupported_extension(tmp_path):
    gen = FileGenerator()
    files = [RenderedFile(relative_path="config.toml", content="[x]\n", header=False)]
    gen.write(files, tmp_path, spec_id="spec_001")
    content = (tmp_path / "config.toml").read_text()
    assert not content.startswith("#")


def test_git_dir_raises_scaffold_error(tmp_path):
    (tmp_path / ".git").mkdir()
    gen = FileGenerator()
    files = [RenderedFile(relative_path="main.py", content="", header=False)]
    with pytest.raises(ScaffoldError, match=r"\.git"):
        gen.write(files, tmp_path, spec_id="spec_001")


def test_git_dir_with_force_writes_files(tmp_path):
    (tmp_path / ".git").mkdir()
    gen = FileGenerator()
    files = [RenderedFile(relative_path="main.py", content="pass\n", header=False)]
    written = gen.write(files, tmp_path, force=True, spec_id="spec_001")
    assert len(written) == 1
    assert (tmp_path / "main.py").exists()


def test_subdirectories_created_automatically(tmp_path):
    gen = FileGenerator()
    files = [RenderedFile(relative_path="a/b/c/deep.py", content="pass\n", header=False)]
    gen.write(files, tmp_path, spec_id="spec_001")
    assert (tmp_path / "a" / "b" / "c" / "deep.py").exists()
