"""FileGenerator — writes RenderedFile objects to disk with safety checks."""
from __future__ import annotations

from pathlib import Path

from agents.scaffolder.structure_generator import RenderedFile

_HEADER_PREFIXES: dict[str, str] = {
    ".py":  "# Generated by Scaffolder Agent from spec {spec_id}",
    ".ts":  "// Generated by Scaffolder Agent from spec {spec_id}",
    ".js":  "// Generated by Scaffolder Agent from spec {spec_id}",
    ".tsx": "// Generated by Scaffolder Agent from spec {spec_id}",
    ".jsx": "// Generated by Scaffolder Agent from spec {spec_id}",
}


class ScaffoldError(Exception):
    """Raised when scaffolding is blocked (e.g. target has a .git directory)."""


class FileGenerator:
    """Writes RenderedFile objects to an output directory."""

    def write(
        self,
        files: list[RenderedFile],
        output_dir: Path,
        force: bool = False,
        spec_id: str = "",
    ) -> list[Path]:
        """Write files to output_dir. Raises ScaffoldError if .git found (unless force=True)."""
        if not force and (output_dir / ".git").exists():
            raise ScaffoldError(
                f"Target directory '{output_dir}' contains a .git repository. "
                "Use force=True to override."
            )

        written: list[Path] = []
        for rf in files:
            dest = output_dir / rf.relative_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            content = rf.content

            if rf.header:
                suffix = Path(rf.relative_path).suffix
                prefix_template = _HEADER_PREFIXES.get(suffix)
                if prefix_template:
                    header_line = prefix_template.format(spec_id=spec_id)
                    content = header_line + "\n" + content

            dest.write_text(content, encoding="utf-8")
            written.append(dest)

        return written
