"""Tests for agents.test_generator.writer.TestWriter."""
import pytest
from pathlib import Path
from agents.test_generator.analyzer import AnalyzedModule, FunctionInfo
from agents.test_generator.planner import TestPlan, TestScenario
from agents.test_generator.writer import TestWriter


def make_plan(tmp_path, tdd_pending=True, scenario_type="happy_path", template="unit", language="python"):
    src = tmp_path / "foo.py"
    output = tmp_path / "tests" / "test_foo.py"
    scenario = TestScenario(
        name="test_greet_happy_path",
        description="Happy path: greet returns a string",
        target_function="greet",
        scenario_type=scenario_type,
        template=template,
        source="code:greet",
        tdd_pending=tdd_pending,
    )
    return TestPlan(
        module_path=src,
        output_path=output,
        language=language,
        scenarios=[scenario],
        estimated_coverage=50,
        fixtures_needed=(template in ("api", "database")),
    )


@pytest.fixture
def writer():
    from agents.test_generator.writer import DEFAULT_TEMPLATES_DIR
    return TestWriter(templates_dir=DEFAULT_TEMPLATES_DIR)


def test_write_creates_output_file(tmp_path, writer):
    plan = make_plan(tmp_path, tdd_pending=False)
    output = writer.write(plan)
    assert output.exists()


def test_write_creates_parent_directory(tmp_path, writer):
    plan = make_plan(tmp_path)
    output = writer.write(plan)
    assert output.parent.is_dir()


def test_write_tdd_pending_contains_pytest_fail(tmp_path, writer):
    plan = make_plan(tmp_path, tdd_pending=True)
    output = writer.write(plan)
    content = output.read_text(encoding="utf-8")
    assert "pytest.fail" in content
    assert "TDD red phase" in content


def test_write_non_tdd_does_not_contain_pytest_fail(tmp_path, writer):
    plan = make_plan(tmp_path, tdd_pending=False)
    output = writer.write(plan)
    content = output.read_text(encoding="utf-8")
    assert "pytest.fail" not in content


def test_write_contains_generated_header(tmp_path, writer):
    plan = make_plan(tmp_path)
    output = writer.write(plan)
    content = output.read_text(encoding="utf-8")
    assert "Generated by TestGeneratorAgent" in content


def test_write_contains_scenario_function_name(tmp_path, writer):
    plan = make_plan(tmp_path, tdd_pending=False)
    output = writer.write(plan)
    content = output.read_text(encoding="utf-8")
    assert "test_greet_happy_path" in content


def test_write_api_template_python(tmp_path, writer):
    plan = make_plan(tmp_path, tdd_pending=False, template="api")
    output = writer.write(plan)
    content = output.read_text(encoding="utf-8")
    assert "API endpoint tests" in content


def test_write_database_template_python(tmp_path, writer):
    plan = make_plan(tmp_path, tdd_pending=False, template="database")
    output = writer.write(plan)
    content = output.read_text(encoding="utf-8")
    assert "Database operation tests" in content


def test_write_typescript_unit_template(tmp_path, writer):
    src = tmp_path / "bar.ts"
    output = tmp_path / "bar.test.ts"
    scenario = TestScenario(
        name="test_greet_happy_path",
        description="greet works",
        target_function="greet",
        scenario_type="happy_path",
        template="unit",
        source="code:greet",
        tdd_pending=True,
    )
    plan = TestPlan(
        module_path=src,
        output_path=output,
        language="typescript",
        scenarios=[scenario],
        estimated_coverage=50,
        fixtures_needed=False,
    )
    output_path = writer.write(plan)
    content = output_path.read_text(encoding="utf-8")
    assert "TDD red phase" in content
    assert "describe" in content


def test_compute_module_import(writer, tmp_path):
    path = tmp_path / "src" / "foo" / "bar.py"
    result = writer._compute_module_import(path)
    assert result.endswith("src.foo.bar") or "bar" in result
